transmission_interval_minutes: 15  # You can change this freely

sampling_interval_seconds: 30      # All sensors sample every 30 seconds
averaging_window_minutes: 5        # All sensors average over 5 minutes

sensors:
  thp_bme280:
    measurements: [temperature, humidity, pressure]

  air_pollution_sps30:
    measurements: [pm1, pm2_5, pm10]

  uv_ltr390:
    measurements: [uv_index, light_intensity]

  wind_sensor:
    measurements: [wind_speed, wind_direction]

  rain_sensor:
    measurements: [rainfall]
